version: '3.8'

services:
  frontend:
    container_name: taskflow-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    container_name: taskflow-backend
    build:
      context: ./backend
    ports:
      - "5001:80"
    command: json-server --watch /app/db.json --port 80